version: 2.1

commands:
  run-all:
    steps:
    - checkout
    - run:
        command: npm ci
    - run:
        command: npm run lint

jobs:

  test-v10:
    docker:
      - image: node:10
    steps:
      - run-all

  test-v12:
    docker:
      - image: node:12
    steps:
      - run-all

  publish-v10:
    docker:
      - image: node:10
    steps:
      - run-all
      - run:
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

workflows:
  test-deploy:
    jobs:
      - test-v10:
          filters:
            tags:
              only: /^v.*/

      - test-v12:
          filters:
            tags:
              only: /^v.*/

      - publish-v10:
          requires:
            - test-v10
            - test-v12
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
