version: 2.1

commands:
  run-all:
    steps:
    - checkout
    - run:
        command: npm ci
    - run:
        command: npm run lint

defaults: &defaults
  working_directory: ~/repo

jobs:
  test-v8:
    <<: *defaults
    docker:
      - image: node:8
    steps:
      - run-all

  test-v10:
    <<: *defaults
    docker:
      - image: node:10
    steps:
      - run-all

  test-v11:
    <<: *defaults
    docker:
      - image: node:11
    steps:
      - run-all

  publish-v8:
    <<: *defaults
    docker:
      - image: node:8
    steps:
      - run-all
      - run:
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          command: npm publish

workflows:
  test-deploy:
    jobs:
      - test-v8:
          filters:
            tags:
              only: /^v.*/

      - test-v10:
          filters:
            tags:
              only: /^v.*/

      - test-v11:
          filters:
            tags:
              only: /^v.*/

      - publish-v8:
          requires:
            - test-v8
            - test-v10
            - test-v11
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
