version: 2.1

commands:
  run-all:
    steps:
    - checkout

    - run:
        name: Install node modules
        command: npm ci

    - run:
        name: Lint
        command: npm run lint

jobs:
  node-v8:
    docker:
      - image: node:8
    steps:
      - run-all
  node-v10:
    docker:
      - image: node:10
    steps:
      - run-all
  node-v11:
    docker:
      - image: node:11
    steps:
      - run-all

workflows:
  node-multi-build:
    jobs:
      - node-v8
      - node-v10
      - node-v11
