---
name: CI

on:
  push:
    branches:
      - '**'
  workflow_call:

permissions:
  contents: read

env:
  HUSKY: '0'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22, 24]

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Node and NPM versions
        run: |
          node --version
          npm --version
      - name: Cache node_modules
        uses: actions/cache@v6
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run lint
      - run: npm run build:types
      - run: npm run prettier:check
